# Generated by Django 3.2.3 on 2021-05-27 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.CharField(max_length=10)),
                ('movie_id', models.IntegerField()),
                ('original_language', models.CharField(max_length=10)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=100)),
                ('popularity', models.IntegerField()),
                ('poster_path', models.CharField(max_length=100)),
                ('release_date', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('recommend', models.CharField(max_length=100)),
                ('book_link', models.CharField(max_length=300)),
                ('book_title', models.CharField(max_length=100)),
                ('like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
